# Generated by Django 5.0.6 on 2024-05-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drf", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="book", options={},),
    ]
