# Generated by Django 5.0.6 on 2024-05-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf", "0002_alter_book_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="owned_date",
            field=models.DateField(null=True, verbose_name="拥有日期"),
        ),
    ]
