# Generated by Django 5.0.6 on 2024-05-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf", "0003_alter_book_owned_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="昵称")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("address", models.CharField(max_length=255, verbose_name="地址")),
            ],
            options={"db_table": "user",},
        ),
    ]
